import { type NextPage } from "next";
import Head from "next/head";
import Nav from "./nav";
import Link from "next/link";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="" />
      </Head>
      <Nav id="home" />
      <div className="hidden fixed w-24 h-screen md:flex items-center left-auto right-5 text-white ">
        <ul className="w-full flex flex-col items-center space-y-4 after:block after:w-0.5 after:h-24 after:mx-auto after:my-4 after:bg-[#ff6ec7] before:block before:w-0.5 before:h-24 before:mx-auto before:my-4 before:bg-[#ff6ec7]">
          <li className="transition-all duration-300 hover:-translate-y-1"><Link target="_blank" className="w-6 h-6 p-1 hover:text-pink-400 hover:mb-5" href={'https://github.com/CALLmeDOMIN'}><i className="icon-github-circled text-3xl" /></Link></li>
          <li className="transition-all duration-300 hover:-translate-y-1"><Link target="_blank" className="w-6 h-6 p-1 hover:text-pink-400 hover:mb-5" href={'https://www.linkedin.com/in/dominik-siero%C5%84-42405a26b/'}><i className="icon-linkedin-squared text-3xl" /></Link></li>
          <li className="transition-all duration-300 hover:-translate-y-1"><Link target="_blank" className="w-6 h-6 p-1 hover:text-pink-400 hover:mb-5" href={''}>abc</Link></li>
        </ul>
      </div>
      <section className="min-h-screen bg-slate-900 ">
        <div className="p-6 md:p-24">
          <h2 className="text-3xl text-gray-300 font-thin">Hi, my name is</h2>
          <h1 className="text-7xl text-[#ff6ec7] font-semibold">Dominik Sieroń.</h1>
          <h2 className="text-4xl text-gray-300 font-thin">I&apos;m a <span className="text-[#ff6ec7]"> web developer. </span></h2>
        </div>
      </section>
      <section id="about" className="min-h-screen p-24 bg-slate-900">
      </section>
    </>
  );
};

export default Home;
