import { type NextPage } from "next";
import Head from "next/head";
import Nav from "./nav";
import Link from "next/link";
import { Html } from "next/document";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="fixed w-10 h-screen flex items-center left-auto right-5 text-white ">
        <ul className="flex flex-col items-center space-y-4 after:content-[''] after:block after:w-0.5 after:h-24 after:mx-auto after:my-4 after:bg-slate-300 before:content-[''] before:block before:w-0.5 before:h-24 before:mx-auto before:my-4 before:bg-slate-300">
          <li><Link className="w-6 h-6 p-1 hover:text-pink-400" href={'github.com/CALLmeDOMIN'}>git</Link></li>
          <li><Link className="w-6 h-6 p-1 hover:text-pink-400" href={'github.com/CALLmeDOMIN'}>in</Link></li>
          <li></li>
        </ul>
      </div>
      <section id="home" className="min-h-screen bg-slate-900 ">
        <div className="p-24">
          <h2 className="text-3xl text-gray-300 font-thin">Hi, my name is</h2>
          <h1 className="text-7xl text-[#ff6ec7] font-semibold">Dominik Sieroń.</h1>
          <h2 className="text-4xl text-gray-300 font-thin">I'm a <span className="text-[#ff6ec7]"> web developer. </span></h2>
        </div>
      </section>
      <section id="about" className="min-h-screen p-24 bg-slate-900">

      </section>
    </>
  );
};

export default Home;
